spring.application.name=
bot.token=
bot.name=
logging.file.path=
logging.level.root=
spring.http.client.max-connections=
spring.http.client.max-connections-per-route=
spring.webflux.httpclient.max-connections=
spring.webflux.httpclient.max-idle-time=
auth.login=
auth.password=
auth.url=
